# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name=b'Atualizado em')),
                ('tipo', models.CharField(choices=[(b'empate', b'EMPATE'), (b'casa', b'CASA'), (b'fora', b'FORA')], max_length=255, verbose_name=b'Tipo')),
                ('acertou', models.BooleanField(default=False, max_length=255, verbose_name=b'Acertou')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name=b'Atualizado em')),
                ('valor', models.FloatField(verbose_name=b'Valor')),
                ('premio', models.FloatField(verbose_name=b'Premio')),
                ('premiado', models.BooleanField(default=False, max_length=255, verbose_name=b'Premiado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilhetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name=b'Atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name=b'Nome')),
                ('local', models.CharField(max_length=255, verbose_name=b'Local')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name=b'Atualizado em')),
                ('local', models.CharField(max_length=255, verbose_name=b'Local')),
                ('data', models.DateTimeField(verbose_name=b'Data')),
                ('status', models.CharField(choices=[(b'aberto', b'ABERTO'), (b'fechado', b'FECHADO')], default=b'aberto', max_length=64, verbose_name=b'Status')),
                ('resultado', models.CharField(blank=True, choices=[(b'empate', b'EMPATE'), (b'casa', b'CASA'), (b'fora', b'FORA')], max_length=64, null=True, verbose_name=b'Resultado')),
                ('valor_total_apostado', models.FloatField(blank=True, default=0.0, null=True, verbose_name=b'Valor total apostado')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='comum.Campeonato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name=b'Atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name=b'Nome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name=b'Atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name=b'Nome')),
                ('local', models.CharField(max_length=255, verbose_name=b'Local')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jogo',
            name='rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='comum.Rodada'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='time_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_mandante', to='comum.Time'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='time_fora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_visitante', to='comum.Time'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='bilhete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to='comum.Bilhete'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.Jogo'),
        ),
    ]
