# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas_realizadas', to='comum.Jogo'),
        ),
        migrations.AlterField(
            model_name='bilhete',
            name='premio',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Premio'),
        ),
    ]
