# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20180421_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilhete',
            name='premio',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name=b'Premio'),
        ),
    ]
